DISTROOVERRIDES =. "poky:"
PACKAGE_CLASSES ?= "package_ipk"

require conf/distro/poky.conf

DISTRO = "platform-test"

DISTRO_FEATURES:remove = "\
    acl \
    alsa \
    bluetooth \
    debuginfod \
    wifi \
    xattr \
    nfs \
    zeroconf \
    pci \
    3g \
    nfc \
    x11 \
    seccomp \
    pulseaudio \
    gobject-introspection-data \
    ldconfig \
    opengl \
    ptest \
    multiarch \
    wayland \
    vulkan \
"

OLDEST_KERNEL = "5.10"
